import bakasable.const.status_code
import bakasable.const.terrain

TILE_SIZE = 32
FRAME_LENGTH = 100

FRESH_TIMEOUT = 5000

PLAYER_WALKING_SPEED = 0.004
SHEEP_WALKING_RANGE = 5
SHEEP_WALKING_SPEED = PLAYER_WALKING_SPEED * 20

MAX_PENDING_UPDATE_INTEREST = 10
